/*
 * docs.test.js — check the documentation against the game it documents.
 *
 * SCRIPT.md and NPCS.md are written by hand, and hand-written documents drift:
 * this suite has already caught a score table that said 700 when the game said
 * 750, a "119-room platform" that had been 124 rooms for a while, and a hint in
 * the vault itself telling players to fill thirteen niches with "the six lesser"
 * treasures. Every claim below is one the game can be asked about directly, so
 * ask it.
 *
 *   node tests/docs.test.js
 */
const fs = require('fs');
const path = require('path');
const GAME = require(path.join(__dirname, '..', 'imbse-data.js'));

let pass = 0, fail = 0;
const ok = (cond, what) => { if (cond) pass++; else { fail++; console.log('  FAIL ' + what); } };
const eq = (a, b, what) => ok(a === b, what + '  (got ' + JSON.stringify(a) +
  ', wanted ' + JSON.stringify(b) + ')');

const DOCS = path.join(__dirname, '..', 'docs');
const read = f => fs.readFileSync(path.join(DOCS, f), 'utf8');
const SCRIPT = read('SCRIPT.md');
const NPCS = read('NPCS.md');
const MAP = read('MAP.md');
const ALL = { 'SCRIPT.md': SCRIPT, 'NPCS.md': NPCS, 'MAP.md': MAP,
  'WALKTHROUGH.md': read('WALKTHROUGH.md') };

console.log('\nTHE DOCUMENTATION');

/* ---- one docs tree, no duplicate editions ---- */
for (const stale of ['original', 'expansion']) {
  ok(!fs.existsSync(path.join(DOCS, stale)),
    'docs/' + stale + ' does not exist — there is one set of documents');
}

/* ---- the rank ladder is the game's ladder ---- */
{
  /* the ranks table only — other tables in this document also lead with a number */
  const section = SCRIPT.split(/^### Ranks$/m)[1] || '';
  const rows = [...section.split(/^#{1,3} /m)[0].matchAll(/^\| (\d+)\+? \| (.+?) \|$/gm)]
    .map(m => [Number(m[1]), m[2].trim()]);
  const ranks = GAME.meta.ranks.filter(r => r[0] > 0);
  eq(rows.length, ranks.length, 'the rank table has a row per rank');
  ranks.forEach(([at, title]) => {
    ok(rows.some(r => r[0] === at && r[1] === title),
      'rank ' + at + ' is documented as "' + title + '"');
  });
}

/* ---- the score table adds up to the score you can get ---- */
{
  const total = SCRIPT.match(/\| \*\*Total\*\* \| \*\*(\d+)\*\* \|/);
  ok(total, 'the score table has a total');
  if (total) eq(Number(total[1]), GAME.meta.maxScore,
    'the documented total is the game\'s maximum score');
}

/* ---- counts the game can be asked for directly ---- */
{
  const rooms = Object.keys(GAME.rooms).length;
  eq(rooms, 124, 'the game has the room count the docs are written against');
  eq(GAME.KEYSTONES.length, 7, 'seven keystone artifacts');
  eq(GAME.LESSER.length, 13, 'thirteen lesser treasures');
  eq(GAME.TREASURES.length, 20, 'twenty treasures in all');
  eq(GAME.meta.maxCarry, 7, 'a carry limit of seven');

  /* every document that states the room count must state the right one */
  for (const [name, text] of Object.entries(ALL)) {
    const wrong = text.match(/\b(?:64|95|119|120|123|125)[- ]room/gi);
    ok(!wrong, name + ' has no stale room count' + (wrong ? ' (' + wrong.join(', ') + ')' : ''));
  }
}

/* ---- phrases that were true once and are not now ---- */
{
  const STALE = [
    [/six lesser/i, 'the lesser treasures were six and are thirteen'],
    [/maximum \*\*700\*\*/i, 'the maximum was 700 and is 750'],
    [/the full 700\b/i, 'the handover was worth 700 and is worth 750'],
    [/700-point scoring/i, 'the scoring was 700-point and is 750-point'],
    [/docs\/original|docs\/expansion/i, 'the duplicate docs tree is gone'],
  ];
  for (const [name, text] of Object.entries(ALL)) {
    for (const [re, why] of STALE) {
      ok(!re.test(text), name + ': ' + why);
    }
  }
}

/* ---- the halls are the size the script says they are ---- */
{
  const claimed = [...SCRIPT.matchAll(/^### Hall (\d) — .+?\*\((\d+) rooms/gm)]
    .map(m => [Number(m[1]), Number(m[2])]);
  eq(claimed.length, 7, 'all seven halls declare a room count');
  eq(claimed.reduce((a, b) => a + b[1], 0), 66,
    'the seven halls total the number the world verifier counts');
}

/* ---- every link in every document goes somewhere ---- */
{
  let checked = 0;
  for (const [name, text] of Object.entries(ALL)) {
    for (const m of text.matchAll(/\]\(([^)#:]+\.md)\)/g)) {
      checked++;
      ok(fs.existsSync(path.join(DOCS, m[1])), name + ' links to ' + m[1]);
    }
  }
  ok(checked > 0, 'the documents cross-reference each other (' + checked + ' links)');
}

/* ---- the generated documents are in step with their generators ---- */
{
  const ROUTE = require(path.join(DOCS, 'verify', 'route-commands.js'));
  ok(ALL['WALKTHROUGH.md'].indexOf('generated by `node tools/build-walkthrough.js`') !== -1,
    'the walkthrough says how to regenerate it');
  ok(MAP.indexOf('tools/build-map.js') !== -1, 'the map says how to regenerate it');
  eq(MAP.match(/\*\*(\d+) rooms\.\*\*/)[1], String(Object.keys(GAME.rooms).length),
    'the map documents every room in the game');
  ok(ROUTE.length > 400, 'the route the walkthrough is built from is present');
}

console.log('\n' + pass + ' passed, ' + fail + ' failed\n');
process.exit(fail ? 1 : 0);
